// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetLastHeartbeat(ctx context.Context, machineID pgtype.Text) (pgtype.Int8, error)
	UpdateLastHeartbeat(ctx context.Context, arg UpdateLastHeartbeatParams) (*Heartbeat, error)
}

var _ Querier = (*Queries)(nil)
